### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by ufon** [musyoka-morris/react-pure-grid#1]
![image](https://cloud.githubusercontent.com/assets/4355972/19838889/5d034698-9ee9-11e6-83e9-f62e427606e1.png)
![image](https://cloud.githubusercontent.com/assets/4355972/19838897/7563481e-9ee9-11e6-90cb-19514d1e0890.png)
All imports are works fine. but this not :(

**Comment by eabricotc** [comment]
+1

**Comment by regenrek** [comment]
Same Problem

`/index.js:1
(function (exports, require, module, __filename, __dirname) { import PureGridProvider from './src/Provider';`

**Comment by matthewhampton** [comment]
+1

This seems to distributing the raw ES6 source code, rather than transpiled code. How is this intended to be used?

**Comment by GabrielLanghans** [comment]
+1

**Comment by NishantDesai1306** [comment]
+1

**Comment by josephrstraub** [comment]
+1

**Comment by takashisite** [comment]
+1

**Comment by Sharlaan** [comment]
+1
webpack seems to reject this import ....

**Comment by gmotyl** [comment]
+1

**Comment by musyoka-morris** [comment]
The import seems to work fine on my environment. I have added a working webpack.config file and urge you to compare it with your configurations.

**Pull Request:** 
If you’ve solved this problem differently and you feel that your solution would benefit the community as a whole, you should definitely consider making a Pull Request

**Comment by manolkalinov** [comment]
+1

**Comment by aemixdp** [comment]
+1

**Comment by curio77** [comment]
+1

Please provide an example of how to use this in the context of a `webpack`-utilizing project that includes `react-pure-grid` as a dependency. Your example lives in the same package as your module and includes its sources directly.

**Comment by weasteam** [comment]
+1

**Comment by skizzo** [comment]
+1

**Comment by Keped** [comment]
+1
